### ISSUE TITLE
Add id generator settings to header

### ISSUE THREAD

**Issue by mojavelinux** [markdown-asciidoc/markdown-to-asciidoc#16]
We should automatically add the following id generator settings to the header (directly below the title or the first line if there is no title) of generated documents:

```
:idprefix:
:idseparator: -
```

This allows the id generator to behave like Markdown, which will ensure that internal cross references work immediately after converting.

Of course, we could make this an option for the converter and then fix up the cross references as needed to match whatever values are provided.

**Comment by bodiam** [comment]
Maybe one day... :)

**Comment by mojavelinux** [comment]
Why close it?

**Comment by mojavelinux** [comment]
It's much better to mark unresolved issues that aren't currently planned for a release against the "Future" milestone. That way, people coming by looking for ways to help know they can give it a shot. If we close unresolved issues, then there's 0 chance anyone will implement it. I recommend only closing issues if we decide we never want to implement it.

**Comment by bodiam** [comment]
I closed it because it's easy having a backlog of items which will never be picked up. I don't agree with the 0% chance: If it's needed by someone, they will find this issue, build it, pick it up, and I'll release a new version. But I don't think it's handy to use the issue system as a 'maybe one day we'll build this place'. 

Having said this: I don't mind reopening it! But at least now you know my reasoning.

**Comment by mojavelinux** [comment]
Understood. I've found the "future" milestone to work really well in other projects because it communicates that it's something worth doing, but just can't be prioritized at the moment. I often browse future tasks looking for something fun to implement when at a hackergarten and stuff like that.
