### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by bodiam** [markdown-asciidoc/markdown-to-asciidoc#54]
Hi @mojavelinux,

What do you think about this library now? It got some newfound love, and we're making it a bit better. 

However, at the moment, it lives under my `nl.jworks` domain, which I don't mind, but I thought something like `org.asciidoctor.converters` or `org.asciidoctor.markdown` (though a bit ironic) might be better package names,

Would there be any issue from your end to use this, and if there's no issue, would you have a suggestion for a package name?

Cheers,
Erik

**Comment by mojavelinux** [comment]
Nice work on the project.

I'm not convinced that org.asciidoctor is the right group ID for this project. That gives the impression that it's a converter for Asciidoctor, which it's not. It's a converter to AsciiDoc, so it doesn't really have a direct relationship to Asciidoctor (nor does it need one). It's also not currently hosted in the Asciidoctor organization on GitHub.

I don't really see why the group ID needs to change. The currently group ID doesn't make it any lesser of a project. Since it's your project, you're free to change the group ID to something other than nl.jworks if that makes you more comfortable. But org.asciidoctor is reserved for projects that are hosted (and need to be hosted) in the Asciidoctor organization.

I do think it's an interesting question whether the AsciiDoc WG should reserve a group ID for AsciiDoc-related projects such as `org.asciidoc.contrib`. I'll raise that in the ongoing brand/trademark usage discussion.

**Comment by bodiam** [comment]
Thanks for your feedback @mojavelinux , appreciate it. I'll think a bit more about what to do with the package name, but for now I'll keep it like this then. 

Thanks again, and also for your work on this project. It's been 10 years ago, but feels like yesterday.

**Comment by mojavelinux** [comment]
Thank you for being a part of this community. Even if you put it down and come back to it later, you'll always be a member of this community. We're lucky to have you!
